version: "3"

services:
  # サービス名
  django:
    build:
      context: .
      dockerfile: containers/Dockerfile # Dockerfileのファイル名

    # 作成するコンテナ名の指定
    container_name: django

    # 使用するポートの設定
    ports:
      - "8001:8000"

    # 対話的なセッションやコマンドラインの操作を許可する
    tty: true

    volumes:
      # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ
      - ./:/root/workspace

    working_dir: /root/workspace/src/sample
    depends_on:
      - db # dbが起動してからdjangoが起動

  # PostgreSQL
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: books_review_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BkReview#5433App
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
