# Generated by Django 4.1 on 2025-11-28 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('position', models.PositiveSmallIntegerField(verbose_name='学習フローSTEP')),
                ('flow_title', models.CharField(max_length=50, verbose_name='STEP名')),
                ('flow_content', models.TextField(max_length=300, verbose_name='STEP内容')),
                ('duration_text', models.CharField(max_length=20, verbose_name='所要時間')),
            ],
            options={
                'verbose_name': '学習フロー',
                'verbose_name_plural': '学習フロー',
                'ordering': ['review', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('rating', models.FloatField(verbose_name='書籍の評価')),
                ('review_title', models.CharField(max_length=30, verbose_name='レビュータイトル')),
                ('body', models.TextField(max_length=5000, verbose_name='レビュー本文')),
                ('recommended_for', models.TextField(max_length=200, verbose_name='おすすめする人')),
                ('post_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='レビュー投稿日')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='reviews.review', verbose_name='レビュー')),
            ],
            options={
                'verbose_name': 'レビューいいね',
                'verbose_name_plural': 'レビューいいね',
            },
        ),
    ]
