# Generated by Django 4.2.20 on 2026-02-17 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewgood',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewgood',
            name='anon_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='未ログイン識別キー'),
        ),
        migrations.AlterField(
            model_name='reviewgood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_goods', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
        migrations.AddConstraint(
            model_name='reviewgood',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('review', 'user'), name='uniq_reviewgood_by_user'),
        ),
        migrations.AddConstraint(
            model_name='reviewgood',
            constraint=models.UniqueConstraint(condition=models.Q(('anon_key__isnull', False)), fields=('review', 'anon_key'), name='uniq_reviewgood_by_anon'),
        ),
        migrations.AddConstraint(
            model_name='reviewgood',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('anon_key__isnull', False), _connector='OR'), name='check_reviewgood_user_or_anon_required'),
        ),
    ]
