# Generated by Django 4.1 on 2025-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('book_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='書籍ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='書籍名')),
                ('book_img', models.URLField(blank=True, max_length=500, null=True, verbose_name='表紙画像')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社')),
                ('release', models.DateField(blank=True, null=True, verbose_name='発行日')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': '書籍カテゴリ',
                'verbose_name_plural': '書籍カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('category_code', models.CharField(max_length=30, unique=True, verbose_name='カテゴリーコード')),
                ('category_name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
